version: "2"

run:
  go: "1.22"
  timeout: 5m
  tests: false

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

linters:
  enable:
    # Default enabled linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional linters for library
    - bodyclose
    - dupl
    - errorlint
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign