version: 2

run:
  tests: false
  timeout: 5m
  skip-dirs:
    - mock

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  gosec:
    excludes:
      - G104

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - opinionated

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dupl
    - errname
    - errorlint
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - goimports
    - gosec
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign

issues:
  exclude-use-default: false
  exclude:
    - 'package-comments: should have a package comment'
    - 'G103: Use of unsafe calls should be audited'
    - 'Line contains TODO/BUG/FIXME'
  exclude-rules:
    - path: internal/abi
      linters:
        - revive
        - unused
        - stylecheck
        - godot
        - unparam
    - path: internal/experiment
      linters:
        - revive
        - govet
        - staticcheck
    - path: (schema|protocol)\.go
      linters:
        - gosec
    - path: _test\.go
      linters:
        - errcheck
        - gosec